spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/youdi?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    banner: false
server:
  port: 8080